version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/change/babel-plugin-cjs-modular-lodash
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          key: v1-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          # --progress=false is faster
          command: npm install --progress=false
      - save_cache:
          key: v1-modules-{{ checksum "package-lock.json" }}
          paths: node_modules
      - run:
          name: Run tests
          command: npm test
